version: "3.8"

services:
  degconverter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5173" # Map host port 3000 to container port 5173. Vite port 5173 in container, host port 3000 in browser
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production