name: Deploy Next.js application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env

      - name: Build docker image
        run: docker build -t nanskee/temp_conversion .

      - name: Login to docker hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Publish image to docker hub
        run: docker push nanskee/temp_conversion:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull nanskee/temp_conversion:latest

      - name: Stop and remove old container if exists
        run: |
          docker ps -a -q --filter "name=temp-conversion-container" | grep -q . && docker rm -f temp-conversion-container || echo "No container to remove"

      - name: Run docker container
        run: docker run -d -p 3000:5173 --name temp-conversion-container nanskee/temp_conversion

      - name: Verify container is running
        run: docker ps -a | grep temp-conversion-container

      - name: Fetch container logs (optional)
        run: docker logs temp-conversion-container
