name: CD 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest --push .

      - name: Run tests
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/myapp:latest npm test

      - name: Deployment to Production
        if: success()
        run: echo "Deployment to production environment has completed successfully."
